# Generated by Django 2.2.6 on 2019-12-03 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baixo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='Guitar/instrumentos')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('estoque', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='Guitar/instrumentos')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('estoque', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Guitar/instrumentos')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpf', models.CharField(max_length=16)),
                ('rg', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Guitarra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to='Guitar/instrumentos')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField()),
                ('estoque', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ComprarGuitarra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comprador', models.CharField(max_length=100)),
                ('quantidade_guitar', models.PositiveIntegerField()),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Guitar.Pagamento')),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Guitar.Guitarra')),
            ],
        ),
        migrations.CreateModel(
            name='ComprarBateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comprador', models.CharField(max_length=100)),
                ('quantidade_drum', models.PositiveIntegerField()),
                ('bateria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Guitar.Bateria')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Guitar.Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='ComprarBaixo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comprador', models.CharField(max_length=100)),
                ('quantidade_baixo', models.PositiveIntegerField()),
                ('baixo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Guitar.Baixo')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Guitar.Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Guitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.CharField(max_length=3)),
                ('nome_guitar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Guitar.ComprarGuitarra')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Bateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.CharField(max_length=3)),
                ('nome_drum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Guitar.ComprarBateria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Baixo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.CharField(max_length=3)),
                ('nome_baixo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Guitar.ComprarBaixo')),
            ],
        ),
    ]
