# Generated by Django 2.2.6 on 2019-12-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guitar', '0002_auto_20191210_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarra',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Guitar/fotos'),
        ),
    ]
