# Generated by Django 2.2.6 on 2019-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guitar', '0003_auto_20191210_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitarra',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Guitar/instrumentos'),
        ),
    ]
